//! Fixture-parity tests for `rocml::chat::render`.
//!
//! Fixtures were generated by feeding the same message/tool inputs through
//! Crane's `AutoTokenizer::apply_chat_template_with_options`, which renders
//! HF-byte-identical output for this template (see the milestone report for
//! the generation procedure). Every case here must match `rendered` byte
//! for byte — that's the whole point of hand-porting the template instead
//! of reimplementing it from reading alone.

use rocml::chat::{render, Message, RenderOpts, Role, Tool, ToolCall};
use serde_json::Value;

const FIXTURES_JSON: &str = include_str!("data/ornith_chat_fixtures.json");

fn message_from_json(v: &Value) -> Message {
    let role = match v["role"].as_str().expect("fixture message missing role") {
        "system" => Role::System,
        "user" => Role::User,
        "assistant" => Role::Assistant,
        "tool" => Role::Tool,
        other => panic!("fixture has unknown role {other:?}"),
    };
    let content = v["content"].as_str().unwrap_or_default().to_string();
    let tool_calls = v
        .get("tool_calls")
        .and_then(Value::as_array)
        .map(|calls| calls.iter().map(tool_call_from_json).collect())
        .unwrap_or_default();
    Message {
        role,
        content,
        tool_calls,
        reasoning_content: None,
    }
}

fn tool_call_from_json(v: &Value) -> ToolCall {
    // Fixture tool_calls are wrapped OpenAI-style: {"function": {name, arguments}}.
    let function = v.get("function").unwrap_or(v);
    ToolCall::new(
        function["name"]
            .as_str()
            .expect("tool_call missing name")
            .to_string(),
        function["arguments"].clone(),
    )
}

fn tool_from_json(v: &Value) -> Tool {
    let function = &v["function"];
    Tool::new(
        function["name"]
            .as_str()
            .expect("tool missing name")
            .to_string(),
        function["description"]
            .as_str()
            .unwrap_or_default()
            .to_string(),
        function["parameters"].clone(),
    )
}

#[test]
fn all_fixture_cases_render_byte_identical() {
    let cases: Vec<Value> = serde_json::from_str(FIXTURES_JSON).expect("fixture JSON");
    assert!(!cases.is_empty(), "fixture file must not be empty");

    for case in &cases {
        let name = case["case_name"].as_str().expect("case_name");
        let messages: Vec<Message> = case["input_messages"]
            .as_array()
            .expect("input_messages")
            .iter()
            .map(message_from_json)
            .collect();
        let tools: Vec<Tool> = case["input_tools"]
            .as_array()
            .map(|tools| tools.iter().map(tool_from_json).collect())
            .unwrap_or_default();
        let opts = RenderOpts {
            add_generation_prompt: case["add_generation_prompt"].as_bool().unwrap_or(false),
            enable_thinking: case["enable_thinking"].as_bool(),
        };
        let expected = case["rendered"].as_str().expect("rendered");

        let actual = render(&messages, &tools, opts)
            .unwrap_or_else(|e| panic!("case {name}: render failed: {e}"));
        assert_eq!(
            actual, expected,
            "case {name}: rendered output diverged from fixture"
        );
    }
}
